### ISSUE TITLE
Adding books returns error

### ISSUE THREAD

**Issue by pizzimathy** [apizzimenti/booklist#1]
Adding books gives the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/booklist", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/booklist/index.py", line 80, in main
    init(parsed)
  File "/usr/local/lib/python3.5/site-packages/booklist/index.py", line 56, in init
    BookEncoder.encode(book.__dict__)
  File "/usr/local/lib/python3.5/site-packages/booklist/book.py", line 44, in encode
    with open(self.path, "r") as f:
AttributeError: 'dict' object has no attribute 'path'
```

**Comment by sunarch** [comment]
I think this issue is resolved.

I believe this issue was in the following place before files were removed in 35ab4430e1d1f4e1bff05d8dfd3c076bd0e0b41a ...

booklist/index.py (L53-56):
```python
   elif args.add:

        book = Book()
        BookEncoder.encode(book.__dict__)
```
booklist/book.py:
- (L40) dictionary passed to instance method `encode(self, book=None)` of BookEncoder, but accessed from the class
    - resulting in the dict loaded into `self` instead of `book`
- (L44) and the non-existent `path` attribute trying to be read from a dict instead of a `Book` instance: `open(self.path, "r") as f:`

---

Files were added back corrected in 83576bd0af87a9ca803007d14f90ab8bce19487c :

bookend/index.py (L55-59):
```python
   elif args.add:

        book = Book()
        encoder = BookEncoder()
        encoder.encode(book.__dict__)
```
